version = 0.1

[default.deploy.parameters]
stack_name = "hakkutsu-api-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
parameter_overrides = "StageName=dev AllowedOrigins=http://localhost:3000 JwtSecret=local-secret"

[prod.deploy.parameters]
stack_name = "hakkutsu-api-prod"
resolve_s3 = true
s3_prefix = "hakkutsu-api-prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"prod\" AllowedOrigins=\"https://hakkutsu-app.vercel.app/\" JwtSecret=\"YkWpoC2nt8ECgHKtYkXo/QaDnd8IadRMO/n1PkiFgjY=\""
image_repositories = []

[prod.global.parameters]
region = "ap-northeast-1"
