version = 0.1

[default.deploy.parameters]
stack_name = "hakkutsu-api-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = true
parameter_overrides = "StageName=dev AllowedOrigins=http://localhost:3000 JwtSecret=local-secret"
