# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: taiyoyamadahackathon
# "service" is the name of this project. This will also be added to your AWS resource names.
service: hakkutsu-api

stages:
  dev:
    params:
      tableName: "users-table-${sls:stage}"
      matchesTableName: "matches-table-${sls:stage}"
      chatsTableName: "chats-table-${sls:stage}"
      messagesTableName: "messages-table-${sls:stage}"
      checkinsTableName: "checkins-table-${sls:stage}"
      reviewsTableName: "reviews-table-${sls:stage}"
      reportsTableName: "reports-table-${sls:stage}"
      recruitmentsTableName: "recruitments-table-${sls:stage}"
      requestsTableName: "requests-table-${sls:stage}"
      restaurantsTableName: "giranomi-restaurants-${sls:stage}"
      postMatchChatsTableName: "giranomi-post-match-chats-${sls:stage}"
      postMatchChatMessagesTableName: "giranomi-post-match-chat-messages-${sls:stage}"
      restaurantSharesTableName: "giranomi-restaurant-shares-${sls:stage}"
      chatParticipantsTableName: "giranomi-chat-participants-${sls:stage}"
      allowedOrigins:
        - 'http://localhost:3000'
        - 'https://hakkutsu-git-develop-tai09to06y-3264s-projects.vercel.app'
      allowedOriginsCsv: 'http://localhost:3000,https://hakkutsu-git-develop-tai09to06y-3264s-projects.vercel.app'
  prod:
    params:
      tableName: "users-table-${sls:stage}"
      matchesTableName: "matches-table-${sls:stage}"
      chatsTableName: "chats-table-${sls:stage}"
      messagesTableName: "messages-table-${sls:stage}"
      checkinsTableName: "checkins-table-${sls:stage}"
      reviewsTableName: "reviews-table-${sls:stage}"
      reportsTableName: "reports-table-${sls:stage}"
      recruitmentsTableName: "recruitments-table-${sls:stage}"
      requestsTableName: "requests-table-${sls:stage}"
      restaurantsTableName: "giranomi-restaurants-${sls:stage}"
      postMatchChatsTableName: "giranomi-post-match-chats-${sls:stage}"
      postMatchChatMessagesTableName: "giranomi-post-match-chat-messages-${sls:stage}"
      restaurantSharesTableName: "giranomi-restaurant-shares-${sls:stage}"
      chatParticipantsTableName: "giranomi-chat-participants-${sls:stage}"
      allowedOrigins:
        - 'https://hakkutsu-app.vercel.app'
      allowedOriginsCsv: 'https://hakkutsu-app.vercel.app'

provider:
  name: aws
  runtime: nodejs20.x
  httpApi:
    cors:
      allowedOrigins: ${param:allowedOrigins}
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
            - Fn::GetAtt: [MatchesTable, Arn]
            - Fn::GetAtt: [ChatsTable, Arn]
            - Fn::GetAtt: [MessagesTable, Arn]
            - Fn::GetAtt: [CheckinsTable, Arn]
            - Fn::GetAtt: [ReviewsTable, Arn]
            - Fn::GetAtt: [ReportsTable, Arn]
            - Fn::GetAtt: [RecruitmentsTable, Arn]
            - Fn::GetAtt: [RequestsTable, Arn]
            - Fn::GetAtt: [RestaurantsTable, Arn]
            - Fn::GetAtt: [PostMatchChatsTable, Arn]
            - Fn::GetAtt: [PostMatchChatMessagesTable, Arn]
            - Fn::GetAtt: [RestaurantSharesTable, Arn]
            - Fn::GetAtt: [ChatParticipantsTable, Arn]
  environment:
    USERS_TABLE: ${param:tableName}
    MATCHES_TABLE: ${param:matchesTableName}
    CHATS_TABLE: ${param:chatsTableName}
    MESSAGES_TABLE: ${param:messagesTableName}
    CHECKINS_TABLE: ${param:checkinsTableName}
    REVIEWS_TABLE: ${param:reviewsTableName}
    REPORTS_TABLE: ${param:reportsTableName}
    RECRUITMENTS_TABLE: ${param:recruitmentsTableName}
    REQUESTS_TABLE: ${param:requestsTableName}
    RESTAURANTS_TABLE: ${param:restaurantsTableName}
    POST_MATCH_CHATS_TABLE: ${param:postMatchChatsTableName}
    POST_MATCH_CHAT_MESSAGES_TABLE: ${param:postMatchChatMessagesTableName}
    RESTAURANT_SHARES_TABLE: ${param:restaurantSharesTableName}
    CHAT_PARTICIPANTS_TABLE: ${param:chatParticipantsTableName}
    SYSTEM_API_TOKEN: ${env:SYSTEM_API_TOKEN, 'local-system-token'}
    JWT_SECRET: ${env:JWT_SECRET, 'change-me-in-prod'}
    ALLOWED_ORIGINS: ${param:allowedOriginsCsv}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: any


resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}

    MatchesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: matchId
            AttributeType: S
        KeySchema:
          - AttributeName: matchId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:matchesTableName}

    ChatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: S
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:chatsTableName}

    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: chatId
            AttributeType: S
          - AttributeName: messageId
            AttributeType: S
        KeySchema:
          - AttributeName: chatId
            KeyType: HASH
          - AttributeName: messageId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:messagesTableName}

    CheckinsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: matchId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: matchId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:checkinsTableName}

    ReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: reviewId
            AttributeType: S
        KeySchema:
          - AttributeName: reviewId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:reviewsTableName}

    ReportsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: reportId
            AttributeType: S
        KeySchema:
          - AttributeName: reportId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:reportsTableName}

    RecruitmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:recruitmentsTableName}

    RequestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:requestsTableName}
    RestaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: restaurant_id
            AttributeType: S
          - AttributeName: venue
            AttributeType: S
          - AttributeName: distance
            AttributeType: N
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: restaurant_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: VenueDistanceIndex
            KeySchema:
              - AttributeName: venue
                KeyType: HASH
              - AttributeName: distance
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: VenueNameIndex
            KeySchema:
              - AttributeName: venue
                KeyType: HASH
              - AttributeName: name
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:restaurantsTableName}
    PostMatchChatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: chat_id
            AttributeType: S
          - AttributeName: match_id
            AttributeType: S
        KeySchema:
          - AttributeName: chat_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: MatchIdIndex
            KeySchema:
              - AttributeName: match_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:postMatchChatsTableName}
    PostMatchChatMessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: message_id
            AttributeType: S
          - AttributeName: chat_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: message_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ChatIdCreatedAtIndex
            KeySchema:
              - AttributeName: chat_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: UserIdCreatedAtIndex
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:postMatchChatMessagesTableName}
    RestaurantSharesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: share_id
            AttributeType: S
          - AttributeName: chat_id
            AttributeType: S
          - AttributeName: restaurant_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: share_id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: ChatIdRestaurantIdIndex
            KeySchema:
              - AttributeName: chat_id
                KeyType: HASH
              - AttributeName: restaurant_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: RestaurantIdCreatedAtIndex
            KeySchema:
              - AttributeName: restaurant_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:restaurantSharesTableName}
    ChatParticipantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: chat_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: chat_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:chatParticipantsTableName}
