# =========================
# hakkutsu-api / serverless.yml
# =========================

org: taiyoyamadahackathon
service: hakkutsu-api

stages:
  default:
    params:
      tableName: "users-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x

  # ✅ v4以降は CORS をここにまとめて書く！
  httpApi:
    cors:
      allowedOrigins:
        - "https://hakkutsu-8u8105n1c-tai09to06y-3264s-projects.vercel.app" # 本番
        - "https://hakkutsu-git-develop-tai09to06y-3264s-projects.vercel.app" # 開発
        - "http://localhost:3000" # ローカル
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE

  # DynamoDB へのアクセス権限
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]

  # 環境変数
  environment:
    USERS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: any

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
