services:
  api:
    build: ./hakkutsu-api
    ports:
      - "4000:4000"
    environment:
      - USERS_TABLE=users-table-dev
      - MATCHES_TABLE=matches-table-dev
      - CHATS_TABLE=chats-table-dev
      - MESSAGES_TABLE=messages-table-dev
      - CHECKINS_TABLE=checkins-table-dev
      - REVIEWS_TABLE=reviews-table-dev
      - REPORTS_TABLE=reports-table-dev
      - JWT_SECRET=dev-secret
      - ALLOWED_ORIGINS=http://localhost:3000
      - DYNAMODB_LOCAL_URL=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1
    depends_on:
      - dynamodb
    restart: on-failure

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data


  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8010:8001"
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    depends_on:
      - dynamodb

volumes:
  dynamodb_data:
